version: '3.8'

services:
  query_performance_api:
    container_name: query_performance_api
    build:
      context: .
      dockerfile: local-dockerfile
    volumes:
      - ./src:/api/src
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      query_performance_db:
        condition: service_started
    networks:
      - local-network

  query_performance_db:
    container_name: query_performance_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "mysqladmin ping -h localhost -uroot -proot | grep 'mysqld is alive'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - local-network

volumes:
  db_data:

networks:
  local-network:
    driver: bridge
